### ISSUE TITLE
The help modal for new features is broken

### ISSUE THREAD

**Issue by stof** [bocoup/test262-report-issue-tracker#10]
### Summary

The help modal for new features is partially hidden by the table header.

### Expected behavior

the modal opens on top

### Actual behavior

...
![image](https://user-images.githubusercontent.com/439401/51906406-5cdc1480-23c4-11e9-93db-38fbf1ca3f7c.png)

### Steps to reproduce

Click on the `?` icon near `new features

### Environment

Firefox 64.0 on Ubuntu.

**Comment by stof** [comment]
The issue is that your modal does not have a zindex at all (and so is at `0` as zindex).

**Comment by isaacdurazo** [comment]
Thank you for filing this issue, @stof. We will address this as soon as possible 👍

**Comment by isaacdurazo** [comment]
Thanks again for reporting this issue. We have resolved it.
