### ISSUE TITLE
[Bug Report?]: filter engines panel isn't sticky

### ISSUE THREAD

**Issue by tkellen** [bocoup/test262-report-issue-tracker#12]
### Summary
Unclear why some parts of the UI are "sticky" when others are not.

### Expected behavior
Thought filter engines panel would stick to the top of the viewport like the features header during scrolling.

### Actual behavior
The filter engines panel disappears during scrolling.

### Steps to reproduce
Scroll the page.

![filter-engines](https://user-images.githubusercontent.com/1004324/54938757-6766e600-4efd-11e9-969e-4b6e73c39f7e.gif)

**Comment by isaacdurazo** [comment]
Thanks for the suggestion @tkellen! We'll address this issue as soon as we can

**Comment by rwaldron** [comment]
Fixed
