### ISSUE TITLE
Test code block is clipped in Safari

### ISSUE THREAD

**Issue by shvaikalesh** [bocoup/test262-report-issue-tracker#13]
<img width="1345" alt="Screenshot 2019-06-08 at 03 29 13" src="https://user-images.githubusercontent.com/5098878/59139727-a9041a80-899d-11e9-951f-a1205936bccb.png">

### Steps to reproduce

1. Navigate to https://test262.report/browse/built-ins/Date
1. Click on `coercion-errors.js`
1. Source code `<iframe>` has size of 950x150px

150px comes from inline styles:

<details>

<summary><code><iframe></code> HTML code</summary>

```html
<iframe title="Embedded JavaScript Source Code" srcdoc="<!doctype html><style>body{margin:0px;font-size:80%}</style><script>window.isPending=true;</script><script src='https://gist-it.appspot.com/github/tc39/test262/blob/f7a3f63270a97deb9d62adfd9b6f1a96e40e6179/test/built-ins/Date/coercion-errors.js?footer=0'></script><script>setTimeout(()=>window.isPending=false,0);</script></html>" scrolling="no" frameborder="0" style="height: 150px;"></iframe>
```

</details>

**NOTE:** Refreshing the [page](https://test262.report/browse/built-ins/Date/coercion-errors.js) fixes the issue.

### DevTools

* No console errors
* No network failures

### Environment

* Safari 12.1 (14607.1.40.1.4), no extensions
* Safari window inner size: 1233x989px
* macOS 10.14.4 (18E226)

**Comment by isaacdurazo** [comment]
Thanks for the report, @shvaikalesh! We'll add this to our to-do's and look into it as soon as week can

**Comment by isaacdurazo** [comment]
@shvaikalesh I've been trying to look into this, but I haven't been able to reproduce. Is this is still present for you? if so, is it persistent?

**Comment by shvaikalesh** [comment]
@isaacdurazo I've emptied the cache and retried: issue still persists. Please make sure you are following the steps: simply opening a test file URL (like [this one](https://test262.report/browse/built-ins/Array/property-cast-number.js), for example) in Safari renders OK.

**Comment by shvaikalesh** [comment]
Retried in Safari 13.1 and Chrome 81: the issue is still there. Please see the GIF:

![Screen Recording 2020-05-08 at 19 08 57](https://user-images.githubusercontent.com/5098878/81426886-860c5880-9162-11ea-9f21-bf94799b9c8c.gif)

Looks like race condition issue. Code block has **no vertical scrollbar**.

I would very much like to continue using https://test262.report in WebKit's bugzilla. If you give me access, I am sure I can fix it this weekend.

_cc_ @rwaldron

**Comment by rwaldron** [comment]
Should be fixed now
