### ISSUE TITLE
Moddable XS is missing from the About page

### ISSUE THREAD

**Issue by tristanHessell** [bocoup/test262-report-issue-tracker#15]
On the about page(https://test262.report/about), the second paragraph details the JS engines under test:
> We are starting with JavaScript conformance tests for the four major JavaScript implementations: ChakraCore, JavaScriptCore, SpiderMonkey and V8.

`Moddable XS` is under test (as seen at https://test262.report/), but is not listed in the about page.

**Comment by rwaldron** [comment]
Thanks for the heads up! Moddable XS was only recently added, so it looks like we "missed a spot".
