### ISSUE TITLE
Some percentages are greater than 100%

### ISSUE THREAD

**Issue by evmiguel** [bocoup/test262-report-issue-tracker#16]
After reading [this article](https://bocoup.com/blog/widening-the-web-with-ecma-402), I went to [https://test262.report/](https://test262.report/) to look at the pass rates on the front page. I see that the percentages are greater than 100%. Is this intentional? Shouldn't the range of percentages be between 0 and 100%?

<img width="1070" alt="Screen Shot 2019-06-24 at 9 55 46 AM" src="https://user-images.githubusercontent.com/2789098/60024727-50ec3a00-9666-11e9-815f-c008274a61ff.png">

**Comment by rwaldron** [comment]
Thanks @evmiguel! This has been addressed :)
