### ISSUE TITLE
Cmd+Click has inconsistent behaviour

### ISSUE THREAD

**Issue by shvaikalesh** [bocoup/test262-report-issue-tracker#17]
### Steps to reproduce

1. Navigate to https://test262.report/browse/built-ins/JSON
2. Cmd+Click on red zone

<img width="326" alt="Screenshot 2019-06-30 at 00 01 33" src="https://user-images.githubusercontent.com/5098878/60444530-1c5c1d80-9c26-11e9-96cf-f7f56a33146a.png">

**NOTE:** Cmd+Click on green zone works as expected.

### Actual behavior

2. Test opens in current tab

**NOTE:** Same issue in Safari 12.1.

### Expected behavior

2. Test opens in new tab

### DevTools

* No console errors
* No network failures

### Environment

* Chrome 77 (3832.0), no extensions
* Chrome window inner size: 1472x947px
* macOS 10.14.4 (18E226)

**Comment by isaacdurazo** [comment]
Thank you for filling this issue, @shvaikalesh. We'll add it to our backlog and will try to address it as soon as possible.

**Comment by rwaldron** [comment]
Fixed by removing the clickability of the whole row, since it did not and would not ever work correctly.
