### ISSUE TITLE
Percentages look wrong

### ISSUE THREAD

**Issue by codehag** [bocoup/test262-report-issue-tracker#20]
### Summary
Percentages are showing over 100% compliance after clicking around a bit. i think what caused it is moving the time period slider, but the bug persisted after reloadinng. I think this just happened, I was looking at it yesterday and the numbers were right...
...

### Expected behavior
Percentages show less than 100% for not fully complying browsers, up to 100%
...

### Actual behavior
<img width="1166" alt="Screenshot 2020-05-15 at 14 55 22" src="https://user-images.githubusercontent.com/26968615/82052612-3c6cc200-96bc-11ea-8e05-e71d2ecbf658.png">

...

### Steps to reproduce
Load the page. Move the time back a couple of days, reload. I am not sure how i got it stuck there
...

### Environment
MacOS, firefox
...

**Comment by rkirsling** [comment]
Yep, this clearly broke on Thursday:
https://test262.report/?date=2020-05-14 and later reproes,
https://test262.report/?date=2020-05-13 and before does not.

It seems almost as if the scores got doubled (though not precisely, and far less for ChakraCore?).

**Comment by rkirsling** [comment]
I don't see how updates to individual tests could cause this, so I'm guessing it's either https://github.com/tc39/test262/pull/2618 or (PR-less commit) https://github.com/tc39/test262/commit/16ce321ba9d40660fc69a7c0ed2512b0be52f4cc that's the culprit?

**Comment by rkirsling** [comment]
Well, whatever the cause was, it looks like this is fixed since https://test262.report/?date=2020-05-16 (so it only affects two days' reports). :smile:

**Comment by rwaldron** [comment]
There was an issue with how totals were being computed, should be resolved now
