### ISSUE TITLE
JSC results in https://test262.report is not updated from 266226

### ISSUE THREAD

**Issue by Constellation** [bocoup/test262-report-issue-tracker#21]
### Summary

It seems that JSC test results in https://test262.report are not updated from revision 266226 for several days (from 8/28)

### Expected behavior

Showing newer results. At the time of writing, tip-of-trunk revision is 266400.

### Actual behavior

Showing older results (266226), and not updated for several days.

### Steps to reproduce

Opening https://test262.report

### Environment

Viewing from macOS Safari.

**Comment by Constellation** [comment]
@rwaldron @isaacdurazo Can anyone take a look?

**Comment by rwaldron** [comment]
Looks like the version updated by Sept 5. The test runner doesn't have any control over the version of the test runner that gets run, it just uses whatever esvu installs that day.
