### ISSUE TITLE
test262.report results are not updated from 2020 12/16

### ISSUE THREAD

**Issue by Constellation** [bocoup/test262-report-issue-tracker#25]
### Summary

test262.report's data is not updated from 2020/12/16

### Expected behavior

Updated daily.

### Actual behavior

Not updated from 12/16.

### Steps to reproduce

Open test262.report to check data

### Environment

N/A

**Comment by rwaldron** [comment]
@Constellation this is a known issue. The Circle CI setup lost its follower, so it's not running builds. I believe @jugglinmike has, or will address this as soon as possible.

**Comment by Constellation** [comment]
@rwaldron Thank you so much :D

**Comment by rwaldron** [comment]
@Constellation no problem!

**Comment by Constellation** [comment]
@rwaldron @jugglinmike Hi! Is there any update on this?

**Comment by Constellation** [comment]
@rwaldron Sorry for troubling you. Do you have an update on this?

**Comment by jugglinmike** [comment]
No update. I will post here when I know more.

**Comment by jugglinmike** [comment]
Automated results collection has been restored

**Comment by Constellation** [comment]
@jugglinmike Awesome! Thanks so much!!!

**Comment by jugglinmike** [comment]
I spoke too soon. Although the system correctly reported results one time this week, it has not repeated the task since. Re-opening until this is resolved.

**Comment by Constellation** [comment]
It seems that some of URLs that were visible are not accessible (e.g. https://test262.report/?date=2021-03-16).

**Comment by Constellation** [comment]
Looks like it is down from 8/15.

**Comment by jugglinmike** [comment]
This project has been posting new test results as of mid-September, so I'm going to close this issue.

> It seems that some of URLs that were visible are not accessible (e.g. https://test262.report/?date=2021-03-16).

That link appears to be working as intended for me, now. If it's still a problem for anyone, please open a new issue
