### ISSUE TITLE
[Feature request] Add UI to group tests per Test262 `feature`

### ISSUE THREAD

**Issue by mathiasbynens** [bocoup/test262-report-issue-tracker#3]
Thanks for this amazing resource (and congrats on launching it)!

Currently, the UI allows browsing the Test262 directory structure.

I’d like to suggest the ability to group tests [per Test262 `feature`](https://github.com/tc39/test262/blob/master/features.txt). For example, if I want to see all `Array.prototype.flat` tests, it would be nice to see all of them grouped together, even if they are not all in the same Test262 directory.

**Comment by nomadtechie** [comment]
@mathiasbynens thanks so much for submitting this request! Integrating feature support is on our backlog - will circle back to this issue when that "feature" is merged :-)

**Comment by leobalter** [comment]
This is now fixed, let us know what do you think, @mathiasbynens! Thanks for reporting this!

**Comment by mathiasbynens** [comment]
This is great!
