### ISSUE TITLE
Test file links point to a 404 page

### ISSUE THREAD

**Issue by bmac** [bocoup/test262-report-issue-tracker#30]
### If you are submitting a feature request:

1. Explain what the feature is and why you think is important and useful.
2. Please provide as much useful information as possible

### Summary

Links to test files int the test262 repo are broken because they point to an outdated branch name.

#### Steps to Reproduce.
1. Navigate to a test report: https://test262.report/browse/language/destructuring/binding/syntax/destructuring-array-parameters-function-arguments-length.js?engines=javascriptcore
2. Click on the external-link-icon next to the test name: `destructuring-array-parameters-function-arguments-length.js`.

### Expected behavior

Link should bring the user to this web page so they user can see the test file in the test262 report.
https://github.com/tc39/test262/blob/main/test/language/destructuring/binding/syntax/destructuring-array-parameters-function-arguments-length.js

### Actual behavior
Link brings the user here and the user sees a 404 page.
https://github.com/tc39/test262/tree/master/test//language/destructuring/binding/syntax/destructuring-array-parameters-function-arguments-length.js

**Comment by jugglinmike** [comment]
Thanks, Brendan! This is fixed, now :)
