### ISSUE TITLE
Add link to this issue tracker in the footer of the site

### ISSUE THREAD

**Issue by cowboy** [bocoup/test262-report-issue-tracker#7]
Because I had no idea this repo existed until @boazsender told me 😉 

Somewhere in here:

![image](https://user-images.githubusercontent.com/54051/48206520-9b6db000-e33c-11e8-90fb-5a5a2cd08967.png)

**Comment by isaacdurazo** [comment]
Thanks for the suggestion @cowboy 👍

**Comment by nomadtechie** [comment]
@cowboy - change is deployed in the latest version!
