### ISSUE TITLE
Update cadence?

### ISSUE THREAD

**Issue by rkirsling** [bocoup/test262-report-issue-tracker#9]
The README says:
> Test262 Report is based on daily runs of Test262 ... in nightly builds of JavaScript engines, and visualizes at-a-glance status of feature implementation progress.

But I haven't noticed an update (at least for JSC results) since the initial launch—has the daily updating yet to commence?

**Comment by rwaldron** [comment]
Thanks for the report. We're in the process of implementing a number of changes to test262.report and decided to disable automatic runs until those changes have been rolled out.

**Comment by michaelficarra** [comment]
It would be helpful to display somewhere build numbers or commit identifiers for each of the engines used.

**Comment by leobalter** [comment]
We now show the Test262 revision and the version used for each engine, including a time stamp when the results were captured.

I believe it might be nice to add a timestamp for the last time we verified for a new version of Test262 or each engine as well. We don't run the tests again if the test262 or the engine are still in the same versions of the latest results.

**Comment by isaacdurazo** [comment]
Daily updates are now working, so I'm closing this issue now. Thanks everyone!
